# General settings
notifications:
  email: false
sudo: false
dist: trusty

# Build matrix
os:
  - linux
  - osx
language: cpp
compiler:
  - clang
  - gcc

# Install, build, and test
script:
  - mkdir build && pushd build
  - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="$HOME/install" ..
  - make -j2
  - make -j2 test CTEST_OUTPUT_ON_FAILURE=1
  - make -j2 install
  - popd
after_success:
  - mkdir -p "$HOME/bin" && ln -s "$(which $GCOV)" "$HOME/bin/gcov" && ls -l "$HOME/bin" && export PATH="$HOME/bin:$PATH" && hash -r
  - mkdir build-coveralls && pushd build-coveralls
  - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_CXX_FLAGS="-march=native" -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON ..
  - make -j2
  - make -j2 coveralls CTEST_OUTPUT_ON_FAILURE=1
  - popd
