#! /bin/bash

# Run "./autogen.sh" to create or recreate all autogenerated
# configuration magic. This should normally not be necessary; in
# general, just running "ninja" will perform all necessary tasks.

rm -f CMakeCache.txt

# Unix Makefiles
cmake -G 'Unix Makefiles'

# Ninja:
#cmake -G Ninja
