#! /bin/bash

# Run "./autogen.sh" to create or recreate all autogenerated
# configuration magic. This should normally not be necessary; in
# general, just running "ninja" will perform all necessary tasks.

rm -f CMakeCache.txt

# Unix Makefiles (build with "make")
cmake -G 'Unix Makefiles'

# Ninja (build with "ninja")
# Note: Ninja is ofteh faster than make, but may not always be available
#cmake -G Ninja
