#! /bin/bash

# Run "./autogen.sh" to create or recreate all autogenerated
# configuration magic. This should normally not be necessary; in
# generally, just running "ninja" should perform all necessary tasks.

rm -f CMakeCache.txt
cmake -G Ninja
