Requirements:
   Vecmathlib requires either GCC 4.7 or Clang 3.1 to build.

After initial checkout:
   Run "./autogen.sh" to create or recreate all autogenerated
   configuration magic. This should otherwise not be necessary.

Build:
   Run "make"
   If using Ninja: run "ninja"

Clean:
   Run "make clean"
   If using Ninja: run "ninja -t clean"

Test:
   ./test

Benchmark:
   ./bench
